messenger4j:
  appSecret:f5c896ea3ff95877acd0bccb4391db6e
  verifyToken:pepe
  pageAccessToken:EAACLVajiejcBAEsQUy2WRNaqSbOUaSTFN5ck8ORsUzj0AtZBK40zNBxuQUKjT2WtgS07se9LgHxWGZBqzZBd4Jdh6xyfJBbSrds9EUEZCZAPGHpxax7p4FrHLyh5LgRPud50TJ0qLOHG5ZB9vlP3ZARLCxtNfJwhqjZAyv0Xyv37OqRZA5yPQ3ZBJg

logging:
  level:
    com:
      github:
        messenger4j: INFO
